const authEventNames = {
  LOGIN_SUCCESFULL: 'LOGIN_SUCCESFULL',
  LOGIN_FAILED: 'LOGIN_FAILED',
  LOGOUT: 'LOGOUT',
  REQUESTED_GOOGLE_LINK: 'REQUESTED_GOOGLE_LINK',
  NOT_AUTHORIZED: 'NOT_AUTHORIZED',
};
