version: "3.9"

services:
  auth_command_service:
    container_name: auth_command_service
    restart: on-failure
    build:
      dockerfile: ./backend/.dev.dockerfile
    command: bun run dev:auth-command
    ports:
      - "${AUTH_COMMANDS_SERVICE_PORT}:${AUTH_COMMANDS_SERVICE_PORT}"
    volumes:
      - "./backend:/app"
    network_mode: host

  auth_query_service:
    container_name: auth_query_service
    build:
      dockerfile: ./backend/.dev.dockerfile
    command: bun run dev:auth-query
    ports:
      - "${AUTH_QUERY_SERVICE_PORT}:${AUTH_QUERY_SERVICE_PORT}"
    volumes:
      - "./backend:/app"
    network_mode: host
  auth_events_service:
    container_name: auth_events_service
    build:
      dockerfile: ./backend/.dev.dockerfile
    command: bun run dev:auth-events
    # ports:
    #   - "${AUTH_QUERY_SERVICE_PORT}:${AUTH_QUERY_SERVICE_PORT}"
    volumes:
      - "./backend:/app"
    network_mode: host
  gateway:
    container_name: gateway
    build:
      dockerfile: ./backend/.dev.dockerfile
    command: bun run dev:gateway
    # ports:
    #   - "${AUTH_QUERY_SERVICE_PORT}:${AUTH_QUERY_SERVICE_PORT}"
    volumes:
      - "./backend:/app"
    network_mode: host

  # backend:
  #   name: backend
  #   driver: bridge
