version: "3.9"

services:
  auth_command_service:
    container_name: auth_command_service
    restart: on-failure
    build:
      dockerfile: ./backend/.dev.dockerfile
    command: bun run dev:auth-command
    expose:
      - ${AUTH_COMMANDS_SERVICE_PORT}
    # ports:
    #   - "${AUTH_COMMANDS_SERVICE_PORT}:${AUTH_COMMANDS_SERVICE_PORT}"
    volumes:
      - "./backend:/app"

  auth_query_service:
    container_name: auth_query_service
    build:
      dockerfile: ./backend/.dev.dockerfile
    command: bun run dev:auth-query
    ports:
      - "${AUTH_QUERY_SERVICE_PORT}:${AUTH_QUERY_SERVICE_PORT}"
    volumes:
      - "./backend:/app"
    expose:
      - ${AUTH_QUERY_SERVICE_PORT}

  auth_events_service:
    container_name: auth_events_service
    build:
      dockerfile: ./backend/.dev.dockerfile
    command: bun run dev:auth-events
    volumes:
      - "./backend:/app"

  gateway:
    container_name: gateway
    build:
      dockerfile: ./backend/.dev.dockerfile
    command: bun run dev:gateway
    ports:
      - "${GATEWAY_PORT}:${GATEWAY_PORT}"
    volumes:
      - "./backend:/app"
