version: '3.9'

services:
  reverse_proxy:
    container_name: reverse_proxy
    restart: always
    image: nginx:1.25.2-alpine
    volumes:
      - ./configs/nginx.dev.conf:/etc/nginx/nginx.conf
    ports:
      - '80:80'
  users_db:
    container_name: users_db
    restart: always
    image: postgres:15.1-alpine

    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PASSWORD: ${POSTGRES_PWD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PORT: 5432
    ports:
      - '5432:5432'
    env_file:
      - .env
    volumes:
      - ${PWD}/data/main/:/data/main/
  token_store:
    container_name: token_store
    image: redis:alpine
    
    ports:
      - '6379:6379'
    volumes:
      - ${PWD}/data/redis/:/data
  message_bus:
    container_name: message_bus
    image: rabbitmq:3-management-alpine
    environment:
      RABBITMQ_USER: mquser
      RABBITMQ_PASSWORD: jaDACjsdflkmsdfKKKK490qfjioqn23rhf
    env_file:
      - .env
    ports:
      - 5672:5672
      - 15672:15672
