version: "3.9"

services:
  # components:
  #   container_name: components-library
  #   restart: on-failure
  #   build:
  #     dockerfile: ./frontend/libs/components/Dockerfile
  #   volumes:
  #     - "./frontend/libs/components/lib:/app/libs/components/lib"
  #     - "./frontend/libs/components/lib-types:/app/libs/components/lib-types"
  #     - "./frontend/libs/components/src:/app/libs/components/src"
  #     - "./frontend/libs/components/tsconfig.ts:/app/libs/components/tsconfig.ts"
  #     - "./frontend/libs/components/vite.config.ts:/app/libs/components/vite.config.ts"
  #     - "./frontend/libs/components/tailwind.config.js:/app/libs/components/tailwind.config.js"
  #     - "./frontend/libs/components/postcss.config.cjs:/app/libs/components/postcss.config.cjs"

  # shared-worker:
  #   container_name: ${PUBLIC_SHARED_WORKER_HOST_NAME}
  #   restart: on-failure
  #   build:
  #     dockerfile: ./frontend/apps/shared-worker/Dockerfile

  #   expose:
  #     - ${PUBLIC_SHARED_WORKER_PORT}
  #   volumes:
  #     - "./frontend/apps/shared-worker/index.ts:/app/apps/shared-worker/index.ts"
  #     - "./frontend/apps/shared-worker/worker.ts:/app/apps/shared-worker/worker.ts"
  #     - "./frontend/apps/shared-worker/out:/app/apps/shared-worker/out"
  #     - "./frontend/apps/shared-worker/tsconfig.json:/app/apps/shared-worker/tsconfig.json"
  #   environment:
  #     - ${PUBLIC_SHARED_WORKER_PORT}

  main-app:
    container_name: ${PUBLIC_FRONTEND_MAIN_APP_HOST}
    build:
      dockerfile: ./frontend/apps/main/Dockerfile
    ports:
      - "${PUBLIC_FRONTEND_MAIN_APP_PORT}:${PUBLIC_FRONTEND_MAIN_APP_PORT}"
    volumes:
      - "./frontend/apps/main/app:/app/frontend/apps/main/app"
      - "./frontend/apps/main/components:/app/frontend/apps/main/components"
      - "./frontend/apps/main/context:/app/frontend/apps/main/context"
      - "./frontend/apps/main/data:/app/frontend/apps/main/data"
      - "./frontend/apps/main/helpers:/app/frontend/apps/main/helpers"
      - "./frontend/apps/main/public:/app/frontend/apps/main/public"
      - "./frontend/apps/main/types:/app/frontend/apps/main/types"
      - "./frontend/apps/main/widgets:/app/frontend/apps/main/widgets"
      - "./frontend/apps/main/theme.ts:/app/frontend/apps/main/theme.ts"
