version: "3.9"

services:
  host-app:
    container_name: host-app
    build:
      dockerfile: ./frontend/.dev.dockerfile
    command: pnpm run dev:host
    ports:
      - "${PUBLIC_FRONTEND_HOST_APP_PORT}:${PUBLIC_FRONTEND_HOST_APP_PORT}"
    volumes:
      - "./frontend:/app"

    network_mode: host
  article-app:
    container_name: article-app
    build:
      dockerfile: ./frontend/.dev.dockerfile
    command: pnpm run dev:article
    ports:
      - "${FRONTEND_ARTICLE_APP_PORT}:${FRONTEND_ARTICLE_APP_PORT}"
    volumes:
      - "./frontend:/app"
    network_mode: host
  blog-app:
    container_name: blog-app
    build:
      dockerfile: ./frontend/.dev.dockerfile
    command: pnpm run dev:blog
    ports:
      - "${FRONTEND_BLOG_APP_PORT}:${FRONTEND_BLOG_APP_PORT}"
    volumes:
      - "./frontend:/app"
    network_mode: host
  footer-app:
    container_name: footer-app
    build:
      dockerfile: ./frontend/.dev.dockerfile
    command: pnpm run dev:footer
    ports:
      - "${FRONTEND_FOOTER_APP_PORT}:${FRONTEND_FOOTER_APP_PORT}"
    volumes:
      - "./frontend:/app"
    network_mode: host
  header-app:
    container_name: header-app
    build:
      dockerfile: ./frontend/.dev.dockerfile
    command: pnpm run dev:header
    ports:
      - "${FRONTEND_HEADER_APP_PORT}:${FRONTEND_HEADER_APP_PORT}"
    volumes:
      - "./frontend:/app"
    network_mode: host
  home-app:
    container_name: home-app
    build:
      dockerfile: ./frontend/.dev.dockerfile
    command: pnpm run dev:home
    ports:
      - "${FRONTEND_HOME_APP_PORT}:${FRONTEND_HOME_APP_PORT}"
    volumes:
      - "./frontend:/app"
    network_mode: host
