metricbeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

metricbeat.modules:
  - module: elasticsearch
    xpack.enabled: false
    period: 10s
    hosts: ${ELASTIC_HOSTS}
    username: ${ELASTIC_USER}
    password: ${ELASTIC_PASSWORD}
    ssl.enabled: false

  - module: kibana
    metricsets:
      - stats
    period: 10s
    hosts: ${KIBANA_HOSTS}
    username: ${ELASTIC_USER}
    password: ${ELASTIC_PASSWORD}
    xpack.enabled: false

  - module: docker
    metricsets:
      - "container"
      - "cpu"
      - "diskio"
      - "healthcheck"
      - "info"
      - "image"
      - "memory"
      - "network"
    hosts: ["unix:///var/run/docker.sock"]
    period: 10s
    enabled: true

processors:
  - add_host_metadata: ~
  - add_docker_metadata: ~

output.elasticsearch:
  hosts: ${ELASTIC_HOSTS}
  username: ${ELASTIC_USER}
  password: ${ELASTIC_PASSWORD}
# #------------------------------- System Module -------------------------------
# - module: system
#   metricsets: ["cpu", "load", "filesystem", "fsstat", "memory", "network", "process", "core", "diskio", "socket"]
#   period: 5s
#   enabled: true
#   processes: ['.*']

#   cpu.metrics:  ["percentages"]
#   core.metrics: ["percentages"]

# #------------------------------- Docker Module -------------------------------
# - module: docker
#   metricsets: ["container", "cpu", "diskio", "healthcheck", "info", "memory", "network"]
#   hosts: ["unix:///var/run/docker.sock"]
#   enabled: true
#   period: 5s

# #-------------------------- Elasticsearch output ------------------------------
# output.elasticsearch:
#   username: "metricbeat_anonymous_user"
#   #password: ""
#   hosts: ["${HOST_ELASTICSEARCH}"]

# setup.kibana:
#   host: "${HOST_KIBANA}"

# #============================== Dashboards =====================================
# # These settings control loading the sample dashboards to the Kibana index. Loading
# # the dashboards is disabled by default and can be enabled either by setting the
# # options here, or by using the `-setup` CLI flag.
# setup.dashboards.enabled: true

# logging.level: warning
# logging.to_files: true
# logging.to_syslog: false
# logging.files:
#   path: /var/log/metricbeat
#   name: metricbeat.log
#   keepfiles: 2
#   permissions: 0644
